### ISSUE TITLE
Change the folder structure

### ISSUE THREAD

**Issue by medic-code** [kkotsche1/Counseling-Dataset-Creation-Finetuning-ALPACA#4]
Note sure if you've thought about the folder structure but worth thinking about it abit more. This comes off the back of providing an easy way for other developers to install the required packages and perhap creating scripts for your model rather than in a jupyter notebook. But also sensibly putting tests etc...

See here for some more details
https://realpython.com/python-application-layouts/#installable-single-package

**Comment by kkotsche1** [comment]
Thank you for sharing the resource! Will take a look and adjust accordingly :) 

Again though - this was merely intended as a way to share my code. As stated in the linkedin post this is not even remotely close to being intended for production or commercial use (which would not be possible due to it being built on the LLaMA basis)

**Comment by medic-code** [comment]
Yep I understand where you're coming from totally. Folder structure can be as simple or complicated as you make it. Taking care when you're writing a hobby project with more than a few files is worth considering the file structure.

Making sure you have a gitignore and package dependency makes it really easy for others to get involved in your code be able to check it out, test it out and collaborate. But also in 2 years time and you want to clone the repo yourself and get going again it makes it really easy.

Just some food for thought!
